### ISSUE TITLE
-truth breaks warn() on 5.20

### ISSUE THREAD

**Issue by dagolden** [ingydotnet/boolean-pm#8]
As discovered by @haarg in https://github.com/Test-More/test-more/issues/546#issuecomment-71968690, `-truth` breaks warn().

```
use boolean -truth;

my $name = 'welp';

my $sub = sub {
  warn "what\n";
  my $str = $name;
};

$sub->();
```

This produces `Warning: something's wrong at test.pl line 6`.

I think modifying the internals is too brittle and "too much magic".  It makes the otherwise useful features of this module risky to depend on.  I suggest deprecating the `-truth` option with some large warnings about how it can break 5.20 and later, and removing it from tests.

**Comment by haarg** [comment]
It doesn't break warn.  It breaks strings.  Warn is just a way to demonstrate that.

**Comment by dagolden** [comment]
@haarg is right.   This only seems to happen on 5.20 with threads enabled.  Here's a clearer example:

```
use strict;
use warnings;
use boolean -truth;

my $name = 'welp';

my $not_broken = sub {
  print "what\n";
};

my $broken = sub {
  print "what\n";
  my $str = $name;
};

print "calling not_broken:\n";
$not_broken->();

print "calling broken:\n";
$broken->();
```

Output on 5.18.2-threads and 5.20.0-nothreads:
```
$ perl boolean-broken.pl
calling not_broken:
what
calling broken:
what
```

Output on 5.20.0-threads:
```
$ perl boolean-broken.pl
calling not_broken:
what
calling broken:
Use of uninitialized value0 in print at boolean-broken.pl line 12.
```

In particular note that the string assignment *after* the print statement causes the string literal `"what\n"` to become undefined.

I've also opened [perlbug 123698](https://rt.perl.org/Ticket/Display.html?id=123698) about it.
